import { windowHeight, windowWidth } from '@/Utilities/helper'
import { StyleSheet, I18nManager } from 'react-native'
import { RFValue } from 'react-native-responsive-fontsize'
export const styles = StyleSheet.create({
  mainContainer: {
    marginHorizontal: windowWidth * 0.1,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    height: windowHeight * 0.57,
    position: 'absolute',
    marginTop: RFValue(60),
    zIndex: 1,
  },
  accountLogin: {
    // fontWeight: 'bold',
    fontSize: RFValue(28),
    fontFamily: 'NotoSansHebrew-Bold',
    color: 'white',
    marginBottom: RFValue(18),
  },
  loginMessage: {
    fontSize: RFValue(14),
    color: 'white',
    // paddingHorizontal: windowWidth * 0.024,
    textAlign: 'center',
    marginBottom: RFValue(54),
    // fontFamily: "NotoSansHebrew-Regular",
  },
  input: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    width: '100%',
    height: RFValue(56),
    borderRadius: 100,
    paddingHorizontal: RFValue(30),
    // marginTop: windowWidth * 0.022,
    color: 'rgba(255,255,255,0.7)',
    fontFamily: 'NotoSansHebrew-Regular',
    padding: 0,
    fontSize: RFValue(16),
    textAlign: I18nManager.isRTL ? 'right' : 'left',
    // // fontFamily: fontFamily,
  },
  loginButton: {
    backgroundColor: '#00C4FF',
    width: '100%',
    height: RFValue(56),
    borderRadius: 100,
    paddingTop: RFValue(2),
    color: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    zIndex: 1,
    // // fontFamily: fontFamily,
  },
  loginButtonText: {
    color: 'white',
    marginRight: RFValue(10),
    fontSize: RFValue(20),
    // paddingHorizontal: windowWidth * 0.017,
    // marginTop: windowWidth * 0.027,
    fontFamily: 'NotoSansHebrew-Bold',
    // backgroundColor: 'red',
    // // fontFamily: fontFamily,
  },
  lottieView: {
    alignItems: 'center',
    marginTop: -windowHeight * 0.37,
  },
  lottie: {
    width: '120%',
    bottom: 40,
  },
  errorTransparent: { opacity: 0 },
  errors: {
    color: '#FF7F7F',
    paddingHorizontal: windowWidth * 0.05,
    marginVertical: RFValue(5),
    fontSize: windowWidth * 0.03,
  },
  errorContainer: {
    width: '100%',
    alignItems: 'flex-start',
  },
  forgotContainer: {
    alignItems: 'center',
    marginTop: windowHeight * 0.04,
  },

  forgotText: {
    // // fontFamily: fontFamily,
    fontFamily: 'NotoSansHebrew-Regular',
    color: '#00C4FF',
    fontSize: RFValue(16),
    marginBottom: RFValue(8),
  },
  protectText: {
    color: '#00C4FF',
    // fontSize: windowHeight * 0.021,
    fontFamily: 'NotoSansHebrew-Bold',
    fontSize: RFValue(18),
    // fontWeight: 'bold',
  },
  appNameBanner: {
    position: 'absolute',
    bottom: RFValue(80),
    alignSelf: 'center',
  },
  backgroundContainer: {
    position: 'absolute',
    bottom: -RFValue(20),
    left: -windowWidth / 5,
  },
  backgroundImage: {
    position: 'absolute',
    bottom: 0,
    flex: 1,
    width: windowWidth / 1.2,
    height: undefined,
    aspectRatio: 0.807,
  },
})
